//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCO.PracticaNET.ReglasNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asignatura()
        {
            this.registroNotas = new HashSet<registroNota>();
        }
    
        public System.Guid id { get; set; }
        public string materia { get; set; }
        public decimal credito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<registroNota> registroNotas { get; set; }
    }
}
