//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCO.PracticaNET.ReglasNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class registroNota
    {
        public System.Guid id { get; set; }
        public System.Guid idEstudiante { get; set; }
        public System.Guid idAsignatura { get; set; }
        public decimal nota { get; set; }
    
        public virtual asignatura asignatura { get; set; }
        public virtual estudiante estudiante { get; set; }
    }
}
