//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCO.PracticaNET.ReglasNegocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UCOPracticasNETEntities : DbContext
    {
        public UCOPracticasNETEntities()
            : base("name=UCOPracticasNETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asignatura> asignaturas { get; set; }
        public virtual DbSet<ciudad> ciudads { get; set; }
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<registroNota> registroNotas { get; set; }
    }
}
